-- V43__insert_villain_names_democracia.sql

INSERT INTO villain_name VALUES (1, 'Burocracia Viviente');
INSERT INTO villain_name VALUES (1, 'Caso de Corrupción');
INSERT INTO villain_name VALUES (1, 'Bestia de Hacienda');
INSERT INTO villain_name VALUES (1, 'Ley Mordaza');
INSERT INTO villain_name VALUES (1, 'Monstruo Mediático');
INSERT INTO villain_name VALUES (1, 'Fantasma del Déficit');
INSERT INTO villain_name VALUES (1, 'Titán de la Deuda Pública');
INSERT INTO villain_name VALUES (1, 'Juez Implacable');
INSERT INTO villain_name VALUES (1, 'Sombra del Sindicalismo Radical');
INSERT INTO villain_name VALUES (1, 'Espectro del Desempleo');
INSERT INTO villain_name VALUES (2, 'Gürtel');
INSERT INTO villain_name VALUES (2, 'ERE Andalucía');
INSERT INTO villain_name VALUES (2, 'Púnica');
INSERT INTO villain_name VALUES (2, 'Kitchen');
INSERT INTO villain_name VALUES (2, 'Malversación Etérea');
INSERT INTO villain_name VALUES (2, 'Trama de los Sobres');
INSERT INTO villain_name VALUES (2, 'Red Clientelar');
INSERT INTO villain_name VALUES (2, 'Manipulador de Contratos');
INSERT INTO villain_name VALUES (2, 'Conseguidor');
INSERT INTO villain_name VALUES (2, 'Fantasma de las Subvenciones');
INSERT INTO villain_name VALUES (3, 'Defensor de los Papeleos');
INSERT INTO villain_name VALUES (3, 'Inspector Impecable');
INSERT INTO villain_name VALUES (3, 'Fiscal Sombrío');
INSERT INTO villain_name VALUES (3, 'Administrador Opaco');
INSERT INTO villain_name VALUES (3, 'Consejo del Olvido');
INSERT INTO villain_name VALUES (3, 'Mesa de Diálogo Eternizada');
INSERT INTO villain_name VALUES (3, 'Agencia del Inmovilismo');
INSERT INTO villain_name VALUES (3, 'Tribunal Variable');
INSERT INTO villain_name VALUES (3, 'Comisión del Retraso Eterno');
INSERT INTO villain_name VALUES (3, 'Secretario Inflexible');
INSERT INTO villain_name VALUES (4, 'Burbuja Inmobiliaria');
INSERT INTO villain_name VALUES (4, 'Preferentista');
INSERT INTO villain_name VALUES (4, 'Mercado Negro');
INSERT INTO villain_name VALUES (4, 'Banco Resucitado');
INSERT INTO villain_name VALUES (4, 'Rescate Financiero');
INSERT INTO villain_name VALUES (4, 'Paro Juvenil');
INSERT INTO villain_name VALUES (4, 'Contrato Basura');
INSERT INTO villain_name VALUES (4, 'Subida del IPC');
INSERT INTO villain_name VALUES (4, 'Crisis de 2008');
INSERT INTO villain_name VALUES (4, 'Reforma Laboral Sombría');
INSERT INTO villain_name VALUES (5, 'Titular Tendencioso');
INSERT INTO villain_name VALUES (5, 'Bulos Virales');
INSERT INTO villain_name VALUES (5, 'Editorial Sesgado');
INSERT INTO villain_name VALUES (5, 'Filtraciones Interesadas');
INSERT INTO villain_name VALUES (5, 'Encuesta Misteriosa');
INSERT INTO villain_name VALUES (5, 'Agenda Oculta');
INSERT INTO villain_name VALUES (5, 'Manipulador de Debate');
INSERT INTO villain_name VALUES (5, 'Panel de Distorsión');
INSERT INTO villain_name VALUES (5, 'Ruido Informativo');
INSERT INTO villain_name VALUES (5, 'Propagador del Miedo');
INSERT INTO villain_name VALUES (6, 'Obras Eternas');
INSERT INTO villain_name VALUES (6, 'Autovía Fantasma');
INSERT INTO villain_name VALUES (6, 'Aeropuerto sin Aviones');
INSERT INTO villain_name VALUES (6, 'AVE con Sobrecoste');
INSERT INTO villain_name VALUES (6, 'Puente Inacabado');
INSERT INTO villain_name VALUES (6, 'Rotonda Infinita');
INSERT INTO villain_name VALUES (6, 'Fantasma Logístico');
INSERT INTO villain_name VALUES (6, 'Pelotón de Subcontratas');
INSERT INTO villain_name VALUES (6, 'Contrato Anulado');
INSERT INTO villain_name VALUES (6, 'Edificio Irregular');
INSERT INTO villain_name VALUES (7, 'Soberanismo Envolvente');
INSERT INTO villain_name VALUES (7, 'Polarizador');
INSERT INTO villain_name VALUES (7, 'Extremista Volátil');
INSERT INTO villain_name VALUES (7, 'Populismo Embrujador');
INSERT INTO villain_name VALUES (7, 'Guerra Cultural');
INSERT INTO villain_name VALUES (7, 'Tensión Territorial');
INSERT INTO villain_name VALUES (7, 'Marea Ideológica');
INSERT INTO villain_name VALUES (7, 'Comité de Expertos Inexistente');
INSERT INTO villain_name VALUES (7, 'Identidad Fragmentada');
INSERT INTO villain_name VALUES (7, 'Presión Callejera');
INSERT INTO villain_name VALUES (8, 'Lista de Espera Infinita');
INSERT INTO villain_name VALUES (8, 'Aula Masificada');
INSERT INTO villain_name VALUES (8, 'Recortes Sociales');
INSERT INTO villain_name VALUES (8, 'Colapso de Servicios');
INSERT INTO villain_name VALUES (8, 'Gestión Caótica');
INSERT INTO villain_name VALUES (8, 'Turnos Eternos');
INSERT INTO villain_name VALUES (8, 'Brecha Digital');
INSERT INTO villain_name VALUES (8, 'Falta de Recursos');
INSERT INTO villain_name VALUES (8, 'Burofax Fallido');
INSERT INTO villain_name VALUES (8, 'Papeleo Telemático');
INSERT INTO villain_name VALUES (9, 'Entropía Bipeda');
INSERT INTO villain_name VALUES (9, 'Contradicción con Patas');
INSERT INTO villain_name VALUES (9, 'Ego Inestable');
INSERT INTO villain_name VALUES (9, 'Sombra de la Autocrítica');
INSERT INTO villain_name VALUES (9, 'Avatar del Autoengaño');
INSERT INTO villain_name VALUES (9, 'Cicatriz Emocional Ambulante');
INSERT INTO villain_name VALUES (9, 'Réplica de la Duda Interna');
INSERT INTO villain_name VALUES (9, 'Ruido Mental Permanente');
INSERT INTO villain_name VALUES (9, 'Espiral de Pensamientos Rotos');
INSERT INTO villain_name VALUES (9, 'Reflejo Imperfecto del Yo');
